# Generated by Django 2.2.7 on 2020-03-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesdetails',
            old_name='salary',
            new_name='esalary',
        ),
    ]
